import type { WorkItemInput } from "./workData";

export const behanceWorkItems = [
  {
    title: "Sync (Gym App)",
    slug: "behance-sync-gym-app",
    href: "https://www.behance.net/gallery/249595451/Sync-%28Gym-App%29",
    source: "Behance",
    sourceUrl: "https://www.behance.net/gallery/249595451/Sync-%28Gym-App%29",
    client: "Sync (Gym App)",
    type: "Figma Design",
    category: "figma-design",
    description:
      "Sync (Gym App) is a Figma UI/UX design case study imported from Behance, published May 18, 2026, with focus areas including Figma, UI Design, UX Design, AI.",
    summary:
      "Sync (Gym App) is a Figma UI/UX design case study imported from Behance, published May 18, 2026, with focus areas including Figma, UI Design, UX Design, AI.",
    scope: "Figma, UI Design",
    outcome: "Design case study",
    visual: "portfolio",
    span: "half",
    tone: "light",
    stats: ["Figma Design", "Figma"],
    year: "Behance",
    duration: "Design",
    team: "UI/UX design",
    headline: "Sync (Gym App)",
    detailIntro:
      "Sync (Gym App) is a Figma UI/UX design case study imported from Behance, published May 18, 2026, with focus areas including Figma, UI Design, UX Design, AI.",
    challenge:
      "Sync (Gym App) is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
    build:
      "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, AI, gym, gym app design, GYM APPLICATION, fitness app. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
    impact:
      "Source: Behance. Published: May 18, 2026. Last updated: May 18, 2026. Profile stats at scrape time: 24 Behance views and 0 appreciations. Original project URL: https://www.behance.net/gallery/249595451/Sync-%28Gym-App%29.",
    modules: [
      "Figma",
      "UI Design",
      "UX Design",
      "AI",
      "gym",
      "gym app design",
      "GYM APPLICATION",
      "fitness app",
    ],
    outcomes: ["Figma design", "UI/UX case study", "Behance source"],
    timeline: [
      {
        label: "Project Overview",
        text: "Sync (Gym App) is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        label: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, AI, gym, gym app design, GYM APPLICATION, fitness app. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        label: "Gallery Assets",
        text: "10 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
    ],
    thumbnail: "/work-images/behance/behance-sync-gym-app-01-3fa6e2cc.png",
    images: [
      "/work-images/behance/behance-sync-gym-app-01-3fa6e2cc.png",
      "/work-images/behance/behance-sync-gym-app-02-01f669c4.webp",
      "/work-images/behance/behance-sync-gym-app-03-ff944486.webp",
      "/work-images/behance/behance-sync-gym-app-04-2b3a1653.webp",
      "/work-images/behance/behance-sync-gym-app-05-422c6685.webp",
      "/work-images/behance/behance-sync-gym-app-06-773408be.webp",
      "/work-images/behance/behance-sync-gym-app-07-444603cb.webp",
      "/work-images/behance/behance-sync-gym-app-08-0acb137c.webp",
      "/work-images/behance/behance-sync-gym-app-09-f263e365.webp",
      "/work-images/behance/behance-sync-gym-app-10-ef816b79.webp",
    ],
    stack: [
      "Figma",
      "UI Design",
      "UX Design",
      "AI",
      "gym",
      "gym app design",
      "GYM APPLICATION",
      "fitness app",
    ],
    detailSections: [
      {
        title: "Project Overview",
        text: "Sync (Gym App) is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        title: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, AI, gym, gym app design, GYM APPLICATION, fitness app. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        title: "Gallery Assets",
        text: "10 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
      {
        title: "Behance Details",
        text: "Source: Behance. Published: May 18, 2026. Last updated: May 18, 2026. Profile stats at scrape time: 24 Behance views and 0 appreciations. Original project URL: https://www.behance.net/gallery/249595451/Sync-%28Gym-App%29.",
      },
    ],
    iconName: "Code2",
  },
  {
    title: "I Grill",
    slug: "behance-i-grill",
    href: "https://www.behance.net/gallery/240342849/I-Grill",
    source: "Behance",
    sourceUrl: "https://www.behance.net/gallery/240342849/I-Grill",
    client: "I Grill",
    type: "Figma Design",
    category: "figma-design",
    description:
      "I Grill is a Figma UI/UX design case study imported from Behance, published December 12, 2025, with focus areas including Figma, UI Design, UX Design, Food.",
    summary:
      "I Grill is a Figma UI/UX design case study imported from Behance, published December 12, 2025, with focus areas including Figma, UI Design, UX Design, Food.",
    scope: "Figma, UI Design",
    outcome: "Design case study",
    visual: "portfolio",
    span: "half",
    tone: "light",
    stats: ["Figma Design", "Figma"],
    year: "Behance",
    duration: "Design",
    team: "UI/UX design",
    headline: "I Grill",
    detailIntro:
      "I Grill is a Figma UI/UX design case study imported from Behance, published December 12, 2025, with focus areas including Figma, UI Design, UX Design, Food.",
    challenge:
      "I Grill is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
    build:
      "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, Food, grilling, cooking, figma design, UI/UX. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
    impact:
      "Source: Behance. Published: December 12, 2025. Last updated: December 12, 2025. Profile stats at scrape time: 36 Behance views and 2 appreciations. Original project URL: https://www.behance.net/gallery/240342849/I-Grill.",
    modules: [
      "Figma",
      "UI Design",
      "UX Design",
      "Food",
      "grilling",
      "cooking",
      "figma design",
      "UI/UX",
    ],
    outcomes: ["Figma design", "UI/UX case study", "Behance source"],
    timeline: [
      {
        label: "Project Overview",
        text: "I Grill is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        label: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, Food, grilling, cooking, figma design, UI/UX. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        label: "Gallery Assets",
        text: "10 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
    ],
    thumbnail: "/work-images/behance/behance-i-grill-01-bce81180.png",
    images: [
      "/work-images/behance/behance-i-grill-01-bce81180.png",
      "/work-images/behance/behance-i-grill-02-e6ab6bc9.webp",
      "/work-images/behance/behance-i-grill-03-1d58a3a2.webp",
      "/work-images/behance/behance-i-grill-04-e2b6deb1.webp",
      "/work-images/behance/behance-i-grill-05-896ac056.webp",
      "/work-images/behance/behance-i-grill-06-0884b384.webp",
      "/work-images/behance/behance-i-grill-07-21294e39.webp",
      "/work-images/behance/behance-i-grill-08-7de86e35.webp",
      "/work-images/behance/behance-i-grill-09-c017502d.webp",
      "/work-images/behance/behance-i-grill-10-34c4fac0.png",
    ],
    stack: [
      "Figma",
      "UI Design",
      "UX Design",
      "Food",
      "grilling",
      "cooking",
      "figma design",
      "UI/UX",
    ],
    detailSections: [
      {
        title: "Project Overview",
        text: "I Grill is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        title: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, Food, grilling, cooking, figma design, UI/UX. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        title: "Gallery Assets",
        text: "10 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
      {
        title: "Behance Details",
        text: "Source: Behance. Published: December 12, 2025. Last updated: December 12, 2025. Profile stats at scrape time: 36 Behance views and 2 appreciations. Original project URL: https://www.behance.net/gallery/240342849/I-Grill.",
      },
    ],
    iconName: "Code2",
  },
  {
    title: "BAQA App",
    slug: "behance-baqa-app",
    href: "https://www.behance.net/gallery/240203303/BAQA-App",
    source: "Behance",
    sourceUrl: "https://www.behance.net/gallery/240203303/BAQA-App",
    client: "BAQA App",
    type: "Figma Design",
    category: "figma-design",
    description:
      "BAQA App is a Figma UI/UX design case study imported from Behance, published December 10, 2025, with focus areas including Figma, UI Design, UX Design, gifts.",
    summary:
      "BAQA App is a Figma UI/UX design case study imported from Behance, published December 10, 2025, with focus areas including Figma, UI Design, UX Design, gifts.",
    scope: "Figma, UI Design",
    outcome: "Design case study",
    visual: "portfolio",
    span: "half",
    tone: "light",
    stats: ["Figma Design", "Figma"],
    year: "Behance",
    duration: "Design",
    team: "UI/UX design",
    headline: "BAQA App",
    detailIntro:
      "BAQA App is a Figma UI/UX design case study imported from Behance, published December 10, 2025, with focus areas including Figma, UI Design, UX Design, gifts.",
    challenge:
      "BAQA App is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
    build:
      "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, gifts, giftsappdesign, mobileappdesign, giftshop, visual identity. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
    impact:
      "Source: Behance. Published: December 10, 2025. Last updated: December 10, 2025. Profile stats at scrape time: 23 Behance views and 0 appreciations. Original project URL: https://www.behance.net/gallery/240203303/BAQA-App.",
    modules: [
      "Figma",
      "UI Design",
      "UX Design",
      "gifts",
      "giftsappdesign",
      "mobileappdesign",
      "giftshop",
      "visual identity",
    ],
    outcomes: ["Figma design", "UI/UX case study", "Behance source"],
    timeline: [
      {
        label: "Project Overview",
        text: "BAQA App is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        label: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, gifts, giftsappdesign, mobileappdesign, giftshop, visual identity. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        label: "Gallery Assets",
        text: "10 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
    ],
    thumbnail: "/work-images/behance/behance-baqa-app-01-adef010f.png",
    images: [
      "/work-images/behance/behance-baqa-app-01-adef010f.png",
      "/work-images/behance/behance-baqa-app-02-ebcb8358.webp",
      "/work-images/behance/behance-baqa-app-03-4b1c1c66.webp",
      "/work-images/behance/behance-baqa-app-04-eabc88c5.webp",
      "/work-images/behance/behance-baqa-app-05-48d172b3.webp",
      "/work-images/behance/behance-baqa-app-06-ef84343e.webp",
      "/work-images/behance/behance-baqa-app-07-5a35caea.webp",
      "/work-images/behance/behance-baqa-app-08-1c3012e1.webp",
      "/work-images/behance/behance-baqa-app-09-83364e39.webp",
      "/work-images/behance/behance-baqa-app-10-ed1a67f1.png",
    ],
    stack: [
      "Figma",
      "UI Design",
      "UX Design",
      "gifts",
      "giftsappdesign",
      "mobileappdesign",
      "giftshop",
      "visual identity",
    ],
    detailSections: [
      {
        title: "Project Overview",
        text: "BAQA App is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        title: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, gifts, giftsappdesign, mobileappdesign, giftshop, visual identity. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        title: "Gallery Assets",
        text: "10 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
      {
        title: "Behance Details",
        text: "Source: Behance. Published: December 10, 2025. Last updated: December 10, 2025. Profile stats at scrape time: 23 Behance views and 0 appreciations. Original project URL: https://www.behance.net/gallery/240203303/BAQA-App.",
      },
    ],
    iconName: "Code2",
  },
  {
    title: "Max Hub E-Commerce",
    slug: "behance-max-hub-e-commerce",
    href: "https://www.behance.net/gallery/235497899/Max-Hub-E-Commerce",
    source: "Behance",
    sourceUrl: "https://www.behance.net/gallery/235497899/Max-Hub-E-Commerce",
    client: "Max Hub E-Commerce",
    type: "Figma Design",
    category: "figma-design",
    description:
      "Max Hub E-Commerce is a Figma UI/UX design case study imported from Behance, published September 27, 2025, with focus areas including Figma, UI Design, UX Design, E commerce Website.",
    summary:
      "Max Hub E-Commerce is a Figma UI/UX design case study imported from Behance, published September 27, 2025, with focus areas including Figma, UI Design, UX Design, E commerce Website.",
    scope: "Figma, UI Design",
    outcome: "Design case study",
    visual: "portfolio",
    span: "half",
    tone: "light",
    stats: ["Figma Design", "Figma"],
    year: "Behance",
    duration: "Design",
    team: "UI/UX design",
    headline: "Max Hub E-Commerce",
    detailIntro:
      "Max Hub E-Commerce is a Figma UI/UX design case study imported from Behance, published September 27, 2025, with focus areas including Figma, UI Design, UX Design, E commerce Website.",
    challenge:
      "Max Hub E-Commerce is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
    build:
      "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, E commerce Website, Web Design, user interface, UI/UX, Shopping. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
    impact:
      "Source: Behance. Published: September 27, 2025. Last updated: September 27, 2025. Profile stats at scrape time: 61 Behance views and 1 appreciations. Original project URL: https://www.behance.net/gallery/235497899/Max-Hub-E-Commerce.",
    modules: [
      "Figma",
      "UI Design",
      "UX Design",
      "E commerce Website",
      "Web Design",
      "user interface",
      "UI/UX",
      "Shopping",
    ],
    outcomes: ["Figma design", "UI/UX case study", "Behance source"],
    timeline: [
      {
        label: "Project Overview",
        text: "Max Hub E-Commerce is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        label: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, E commerce Website, Web Design, user interface, UI/UX, Shopping. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        label: "Gallery Assets",
        text: "10 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
    ],
    thumbnail: "/work-images/behance/behance-max-hub-e-commerce-01-53840ada.png",
    images: [
      "/work-images/behance/behance-max-hub-e-commerce-01-53840ada.png",
      "/work-images/behance/behance-max-hub-e-commerce-02-e4a6d1b2.webp",
      "/work-images/behance/behance-max-hub-e-commerce-03-3320f537.webp",
      "/work-images/behance/behance-max-hub-e-commerce-04-be462216.webp",
      "/work-images/behance/behance-max-hub-e-commerce-05-e16a2c66.webp",
      "/work-images/behance/behance-max-hub-e-commerce-06-c161c13d.webp",
      "/work-images/behance/behance-max-hub-e-commerce-07-48a39481.webp",
      "/work-images/behance/behance-max-hub-e-commerce-08-944768cc.webp",
      "/work-images/behance/behance-max-hub-e-commerce-09-8eafbfc5.webp",
      "/work-images/behance/behance-max-hub-e-commerce-10-60c0324c.webp",
    ],
    stack: [
      "Figma",
      "UI Design",
      "UX Design",
      "E commerce Website",
      "Web Design",
      "user interface",
      "UI/UX",
      "Shopping",
    ],
    detailSections: [
      {
        title: "Project Overview",
        text: "Max Hub E-Commerce is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        title: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, E commerce Website, Web Design, user interface, UI/UX, Shopping. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        title: "Gallery Assets",
        text: "10 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
      {
        title: "Behance Details",
        text: "Source: Behance. Published: September 27, 2025. Last updated: September 27, 2025. Profile stats at scrape time: 61 Behance views and 1 appreciations. Original project URL: https://www.behance.net/gallery/235497899/Max-Hub-E-Commerce.",
      },
    ],
    iconName: "Code2",
  },
  {
    title: "Naqlty App",
    slug: "behance-naqlty-app",
    href: "https://www.behance.net/gallery/232673137/Naqlty-App",
    source: "Behance",
    sourceUrl: "https://www.behance.net/gallery/232673137/Naqlty-App",
    client: "Naqlty App",
    type: "Figma Design",
    category: "figma-design",
    description:
      "Naqlty App is a Figma UI/UX design case study imported from Behance, published August 17, 2025, with focus areas including Figma, UI Design, UX Design, Logistics.",
    summary:
      "Naqlty App is a Figma UI/UX design case study imported from Behance, published August 17, 2025, with focus areas including Figma, UI Design, UX Design, Logistics.",
    scope: "Figma, UI Design",
    outcome: "Design case study",
    visual: "portfolio",
    span: "half",
    tone: "light",
    stats: ["Figma Design", "Figma"],
    year: "Behance",
    duration: "Design",
    team: "UI/UX design",
    headline: "Naqlty App",
    detailIntro:
      "Naqlty App is a Figma UI/UX design case study imported from Behance, published August 17, 2025, with focus areas including Figma, UI Design, UX Design, Logistics.",
    challenge:
      "Naqlty App is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
    build:
      "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, Logistics, shipping, delivery, UI/UX, Interaction Design. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
    impact:
      "Source: Behance. Published: August 17, 2025. Last updated: September 27, 2025. Profile stats at scrape time: 97 Behance views and 4 appreciations. Original project URL: https://www.behance.net/gallery/232673137/Naqlty-App.",
    modules: [
      "Figma",
      "UI Design",
      "UX Design",
      "Logistics",
      "shipping",
      "delivery",
      "UI/UX",
      "Interaction Design",
    ],
    outcomes: ["Figma design", "UI/UX case study", "Behance source"],
    timeline: [
      {
        label: "Project Overview",
        text: "Naqlty App is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        label: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, Logistics, shipping, delivery, UI/UX, Interaction Design. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        label: "Gallery Assets",
        text: "10 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
    ],
    thumbnail: "/work-images/behance/behance-naqlty-app-01-8f1ad91e.png",
    images: [
      "/work-images/behance/behance-naqlty-app-01-8f1ad91e.png",
      "/work-images/behance/behance-naqlty-app-02-961069ed.webp",
      "/work-images/behance/behance-naqlty-app-03-e5ce16fb.webp",
      "/work-images/behance/behance-naqlty-app-04-478eecc3.webp",
      "/work-images/behance/behance-naqlty-app-05-0bdbf1c4.webp",
      "/work-images/behance/behance-naqlty-app-06-00709142.webp",
      "/work-images/behance/behance-naqlty-app-07-bc0d4ff6.webp",
      "/work-images/behance/behance-naqlty-app-08-03a71add.webp",
      "/work-images/behance/behance-naqlty-app-09-0d90e86c.webp",
      "/work-images/behance/behance-naqlty-app-10-3a0ed114.webp",
    ],
    stack: [
      "Figma",
      "UI Design",
      "UX Design",
      "Logistics",
      "shipping",
      "delivery",
      "UI/UX",
      "Interaction Design",
    ],
    detailSections: [
      {
        title: "Project Overview",
        text: "Naqlty App is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        title: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, Logistics, shipping, delivery, UI/UX, Interaction Design. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        title: "Gallery Assets",
        text: "10 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
      {
        title: "Behance Details",
        text: "Source: Behance. Published: August 17, 2025. Last updated: September 27, 2025. Profile stats at scrape time: 97 Behance views and 4 appreciations. Original project URL: https://www.behance.net/gallery/232673137/Naqlty-App.",
      },
    ],
    iconName: "Code2",
  },
  {
    title: "( logistic platform ) نقلتي",
    slug: "behance-logistic-platform",
    href: "https://www.behance.net/gallery/232671997/%28-logistic-platform-%29-",
    source: "Behance",
    sourceUrl: "https://www.behance.net/gallery/232671997/%28-logistic-platform-%29-",
    client: "( logistic platform ) نقلتي",
    type: "Figma Design",
    category: "figma-design",
    description:
      "( logistic platform ) نقلتي is a Figma UI/UX design case study imported from Behance, published August 17, 2025, with focus areas including Figma, UI Design, UX Design, Logistics.",
    summary:
      "( logistic platform ) نقلتي is a Figma UI/UX design case study imported from Behance, published August 17, 2025, with focus areas including Figma, UI Design, UX Design, Logistics.",
    scope: "Figma, UI Design",
    outcome: "Design case study",
    visual: "portfolio",
    span: "half",
    tone: "light",
    stats: ["Figma Design", "Figma"],
    year: "Behance",
    duration: "Design",
    team: "UI/UX design",
    headline: "( logistic platform ) نقلتي",
    detailIntro:
      "( logistic platform ) نقلتي is a Figma UI/UX design case study imported from Behance, published August 17, 2025, with focus areas including Figma, UI Design, UX Design, Logistics.",
    challenge:
      "( logistic platform ) نقلتي is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
    build:
      "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, Logistics, Transport, delivery, ui design, Interaction Design. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
    impact:
      "Source: Behance. Published: August 17, 2025. Last updated: August 17, 2025. Profile stats at scrape time: 50 Behance views and 3 appreciations. Original project URL: https://www.behance.net/gallery/232671997/%28-logistic-platform-%29-.",
    modules: [
      "Figma",
      "UI Design",
      "UX Design",
      "Logistics",
      "Transport",
      "delivery",
      "ui design",
      "Interaction Design",
    ],
    outcomes: ["Figma design", "UI/UX case study", "Behance source"],
    timeline: [
      {
        label: "Project Overview",
        text: "( logistic platform ) نقلتي is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        label: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, Logistics, Transport, delivery, ui design, Interaction Design. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        label: "Gallery Assets",
        text: "10 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
    ],
    thumbnail: "/work-images/behance/behance-logistic-platform-01-73302fe7.png",
    images: [
      "/work-images/behance/behance-logistic-platform-01-73302fe7.png",
      "/work-images/behance/behance-logistic-platform-02-cd32668f.webp",
      "/work-images/behance/behance-logistic-platform-03-50ba70aa.webp",
      "/work-images/behance/behance-logistic-platform-04-6605ec65.webp",
      "/work-images/behance/behance-logistic-platform-05-b378cbeb.webp",
      "/work-images/behance/behance-logistic-platform-06-996d9a1e.webp",
      "/work-images/behance/behance-logistic-platform-07-38dccf15.webp",
      "/work-images/behance/behance-logistic-platform-08-d878e0bd.webp",
      "/work-images/behance/behance-logistic-platform-09-1b72bd49.webp",
      "/work-images/behance/behance-logistic-platform-10-a8a3a7ae.webp",
    ],
    stack: [
      "Figma",
      "UI Design",
      "UX Design",
      "Logistics",
      "Transport",
      "delivery",
      "ui design",
      "Interaction Design",
    ],
    detailSections: [
      {
        title: "Project Overview",
        text: "( logistic platform ) نقلتي is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        title: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, Logistics, Transport, delivery, ui design, Interaction Design. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        title: "Gallery Assets",
        text: "10 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
      {
        title: "Behance Details",
        text: "Source: Behance. Published: August 17, 2025. Last updated: August 17, 2025. Profile stats at scrape time: 50 Behance views and 3 appreciations. Original project URL: https://www.behance.net/gallery/232671997/%28-logistic-platform-%29-.",
      },
    ],
    iconName: "Code2",
  },
  {
    title: "E-coomerce",
    slug: "behance-e-coomerce",
    href: "https://www.behance.net/gallery/225610083/E-coomerce",
    source: "Behance",
    sourceUrl: "https://www.behance.net/gallery/225610083/E-coomerce",
    client: "E-coomerce",
    type: "Figma Design",
    category: "figma-design",
    description:
      "E-coomerce is a Figma UI/UX design case study imported from Behance, published May 11, 2025, with focus areas including Figma, UI Design, UX Design, E COMMERCE.",
    summary:
      "E-coomerce is a Figma UI/UX design case study imported from Behance, published May 11, 2025, with focus areas including Figma, UI Design, UX Design, E COMMERCE.",
    scope: "Figma, UI Design",
    outcome: "Design case study",
    visual: "portfolio",
    span: "half",
    tone: "light",
    stats: ["Figma Design", "Figma"],
    year: "Behance",
    duration: "Design",
    team: "UI/UX design",
    headline: "E-coomerce",
    detailIntro:
      "E-coomerce is a Figma UI/UX design case study imported from Behance, published May 11, 2025, with focus areas including Figma, UI Design, UX Design, E COMMERCE.",
    challenge:
      "E-coomerce is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
    build:
      "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, E COMMERCE, UI/UX, user interface, ui design, landing page. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
    impact:
      "Source: Behance. Published: May 11, 2025. Last updated: July 4, 2025. Profile stats at scrape time: 589 Behance views and 59 appreciations. Original project URL: https://www.behance.net/gallery/225610083/E-coomerce.",
    modules: [
      "Figma",
      "UI Design",
      "UX Design",
      "E COMMERCE",
      "UI/UX",
      "user interface",
      "ui design",
      "landing page",
    ],
    outcomes: ["Figma design", "UI/UX case study", "Behance source"],
    timeline: [
      {
        label: "Project Overview",
        text: "E-coomerce is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        label: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, E COMMERCE, UI/UX, user interface, ui design, landing page. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        label: "Gallery Assets",
        text: "10 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
    ],
    thumbnail: "/work-images/behance/behance-e-coomerce-01-fe5bcee5.png",
    images: [
      "/work-images/behance/behance-e-coomerce-01-fe5bcee5.png",
      "/work-images/behance/behance-e-coomerce-02-0562dfff.webp",
      "/work-images/behance/behance-e-coomerce-03-b21b2ba7.webp",
      "/work-images/behance/behance-e-coomerce-04-6c273a5c.webp",
      "/work-images/behance/behance-e-coomerce-05-36b3271c.webp",
      "/work-images/behance/behance-e-coomerce-06-ce40cf09.png",
      "/work-images/behance/behance-e-coomerce-07-588e35da.webp",
      "/work-images/behance/behance-e-coomerce-08-3dfb99ea.png",
      "/work-images/behance/behance-e-coomerce-09-93022731.webp",
      "/work-images/behance/behance-e-coomerce-10-83eba2cf.png",
    ],
    stack: [
      "Figma",
      "UI Design",
      "UX Design",
      "E COMMERCE",
      "UI/UX",
      "user interface",
      "ui design",
      "landing page",
    ],
    detailSections: [
      {
        title: "Project Overview",
        text: "E-coomerce is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        title: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, E COMMERCE, UI/UX, user interface, ui design, landing page. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        title: "Gallery Assets",
        text: "10 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
      {
        title: "Behance Details",
        text: "Source: Behance. Published: May 11, 2025. Last updated: July 4, 2025. Profile stats at scrape time: 589 Behance views and 59 appreciations. Original project URL: https://www.behance.net/gallery/225610083/E-coomerce.",
      },
    ],
    iconName: "Code2",
  },
  {
    title: "INOVENT",
    slug: "behance-inovent",
    href: "https://www.behance.net/gallery/216546745/INOVENT",
    source: "Behance",
    sourceUrl: "https://www.behance.net/gallery/216546745/INOVENT",
    client: "INOVENT",
    type: "Figma Design",
    category: "figma-design",
    description:
      "INOVENT is a Figma UI/UX design case study imported from Behance, published January 10, 2025, with focus areas including Figma, UI Design, UX Design, Web Design.",
    summary:
      "INOVENT is a Figma UI/UX design case study imported from Behance, published January 10, 2025, with focus areas including Figma, UI Design, UX Design, Web Design.",
    scope: "Figma, UI Design",
    outcome: "Design case study",
    visual: "portfolio",
    span: "half",
    tone: "light",
    stats: ["Figma Design", "Figma"],
    year: "Behance",
    duration: "Design",
    team: "UI/UX design",
    headline: "INOVENT",
    detailIntro:
      "INOVENT is a Figma UI/UX design case study imported from Behance, published January 10, 2025, with focus areas including Figma, UI Design, UX Design, Web Design.",
    challenge:
      "INOVENT is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
    build:
      "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, Web Design, UI/UX, ui design, user interface, landing page. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
    impact:
      "Source: Behance. Published: January 10, 2025. Last updated: May 12, 2025. Profile stats at scrape time: 99 Behance views and 12 appreciations. Original project URL: https://www.behance.net/gallery/216546745/INOVENT.",
    modules: [
      "Figma",
      "UI Design",
      "UX Design",
      "Web Design",
      "UI/UX",
      "ui design",
      "user interface",
      "landing page",
    ],
    outcomes: ["Figma design", "UI/UX case study", "Behance source"],
    timeline: [
      {
        label: "Project Overview",
        text: "INOVENT is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        label: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, Web Design, UI/UX, ui design, user interface, landing page. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        label: "Gallery Assets",
        text: "10 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
    ],
    thumbnail: "/work-images/behance/behance-inovent-01-f1af0204.png",
    images: [
      "/work-images/behance/behance-inovent-01-f1af0204.png",
      "/work-images/behance/behance-inovent-02-367eaa24.webp",
      "/work-images/behance/behance-inovent-03-19291651.webp",
      "/work-images/behance/behance-inovent-04-c02b4c9f.webp",
      "/work-images/behance/behance-inovent-05-f8046dcf.webp",
      "/work-images/behance/behance-inovent-06-5ffe1247.webp",
      "/work-images/behance/behance-inovent-07-2186c213.webp",
      "/work-images/behance/behance-inovent-08-17783bb9.png",
      "/work-images/behance/behance-inovent-09-83153631.webp",
      "/work-images/behance/behance-inovent-10-7127c457.png",
    ],
    stack: [
      "Figma",
      "UI Design",
      "UX Design",
      "Web Design",
      "UI/UX",
      "ui design",
      "user interface",
      "landing page",
    ],
    detailSections: [
      {
        title: "Project Overview",
        text: "INOVENT is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        title: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, Web Design, UI/UX, ui design, user interface, landing page. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        title: "Gallery Assets",
        text: "10 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
      {
        title: "Behance Details",
        text: "Source: Behance. Published: January 10, 2025. Last updated: May 12, 2025. Profile stats at scrape time: 99 Behance views and 12 appreciations. Original project URL: https://www.behance.net/gallery/216546745/INOVENT.",
      },
    ],
    iconName: "Code2",
  },
  {
    title: "أولادنا ( E-Commerce )",
    slug: "behance-e-commerce",
    href: "https://www.behance.net/gallery/215998751/-%28-E-Commerce-%29",
    source: "Behance",
    sourceUrl: "https://www.behance.net/gallery/215998751/-%28-E-Commerce-%29",
    client: "أولادنا ( E-Commerce )",
    type: "Figma Design",
    category: "figma-design",
    description:
      "أولادنا ( E-Commerce ) is a Figma UI/UX design case study imported from Behance, published January 3, 2025, with focus areas including Figma, UI Design, UX Design, E commerce Website.",
    summary:
      "أولادنا ( E-Commerce ) is a Figma UI/UX design case study imported from Behance, published January 3, 2025, with focus areas including Figma, UI Design, UX Design, E commerce Website.",
    scope: "Figma, UI Design",
    outcome: "Design case study",
    visual: "portfolio",
    span: "half",
    tone: "light",
    stats: ["Figma Design", "Figma"],
    year: "Behance",
    duration: "Design",
    team: "UI/UX design",
    headline: "أولادنا ( E-Commerce )",
    detailIntro:
      "أولادنا ( E-Commerce ) is a Figma UI/UX design case study imported from Behance, published January 3, 2025, with focus areas including Figma, UI Design, UX Design, E commerce Website.",
    challenge:
      "أولادنا ( E-Commerce ) is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
    build:
      "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, E commerce Website, UI/UX, landing page, Web Design, ui design. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
    impact:
      "Source: Behance. Published: January 3, 2025. Last updated: May 16, 2025. Profile stats at scrape time: 130 Behance views and 17 appreciations. Original project URL: https://www.behance.net/gallery/215998751/-%28-E-Commerce-%29.",
    modules: [
      "Figma",
      "UI Design",
      "UX Design",
      "E commerce Website",
      "UI/UX",
      "landing page",
      "Web Design",
      "ui design",
    ],
    outcomes: ["Figma design", "UI/UX case study", "Behance source"],
    timeline: [
      {
        label: "Project Overview",
        text: "أولادنا ( E-Commerce ) is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        label: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, E commerce Website, UI/UX, landing page, Web Design, ui design. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        label: "Gallery Assets",
        text: "10 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
    ],
    thumbnail: "/work-images/behance/behance-e-commerce-01-0377fc3b.png",
    images: [
      "/work-images/behance/behance-e-commerce-01-0377fc3b.png",
      "/work-images/behance/behance-e-commerce-02-9bb6021e.webp",
      "/work-images/behance/behance-e-commerce-03-b97b3846.webp",
      "/work-images/behance/behance-e-commerce-04-eeb8175a.webp",
      "/work-images/behance/behance-e-commerce-05-8bd64eec.webp",
      "/work-images/behance/behance-e-commerce-06-8ab55c19.png",
      "/work-images/behance/behance-e-commerce-07-df6198a5.webp",
      "/work-images/behance/behance-e-commerce-08-5a941b0b.webp",
      "/work-images/behance/behance-e-commerce-09-4c4928ac.png",
      "/work-images/behance/behance-e-commerce-10-a6b40300.webp",
    ],
    stack: [
      "Figma",
      "UI Design",
      "UX Design",
      "E commerce Website",
      "UI/UX",
      "landing page",
      "Web Design",
      "ui design",
    ],
    detailSections: [
      {
        title: "Project Overview",
        text: "أولادنا ( E-Commerce ) is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        title: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, E commerce Website, UI/UX, landing page, Web Design, ui design. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        title: "Gallery Assets",
        text: "10 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
      {
        title: "Behance Details",
        text: "Source: Behance. Published: January 3, 2025. Last updated: May 16, 2025. Profile stats at scrape time: 130 Behance views and 17 appreciations. Original project URL: https://www.behance.net/gallery/215998751/-%28-E-Commerce-%29.",
      },
    ],
    iconName: "Code2",
  },
  {
    title: "Test System",
    slug: "behance-test-system",
    href: "https://www.behance.net/gallery/214714449/Test-System",
    source: "Behance",
    sourceUrl: "https://www.behance.net/gallery/214714449/Test-System",
    client: "Test System",
    type: "Figma Design",
    category: "figma-design",
    description:
      "Test System is a Figma UI/UX design case study imported from Behance, published December 13, 2024, with focus areas including Figma, UI Design, UX Design, test.",
    summary:
      "Test System is a Figma UI/UX design case study imported from Behance, published December 13, 2024, with focus areas including Figma, UI Design, UX Design, test.",
    scope: "Figma, UI Design",
    outcome: "Design case study",
    visual: "portfolio",
    span: "half",
    tone: "light",
    stats: ["Figma Design", "Figma"],
    year: "Behance",
    duration: "Design",
    team: "UI/UX design",
    headline: "Test System",
    detailIntro:
      "Test System is a Figma UI/UX design case study imported from Behance, published December 13, 2024, with focus areas including Figma, UI Design, UX Design, test.",
    challenge:
      "Test System is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
    build:
      "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, test, system design, UI/UX, ui design, tests. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
    impact:
      "Source: Behance. Published: December 13, 2024. Last updated: December 26, 2024. Profile stats at scrape time: 32 Behance views and 4 appreciations. Original project URL: https://www.behance.net/gallery/214714449/Test-System.",
    modules: [
      "Figma",
      "UI Design",
      "UX Design",
      "test",
      "system design",
      "UI/UX",
      "ui design",
      "tests",
    ],
    outcomes: ["Figma design", "UI/UX case study", "Behance source"],
    timeline: [
      {
        label: "Project Overview",
        text: "Test System is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        label: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, test, system design, UI/UX, ui design, tests. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        label: "Gallery Assets",
        text: "7 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
    ],
    thumbnail: "/work-images/behance/behance-test-system-01-d3043538.png",
    images: [
      "/work-images/behance/behance-test-system-01-d3043538.png",
      "/work-images/behance/behance-test-system-02-8b976af8.webp",
      "/work-images/behance/behance-test-system-03-4bffe335.webp",
      "/work-images/behance/behance-test-system-04-4d7fca00.png",
      "/work-images/behance/behance-test-system-05-2edf33e8.webp",
      "/work-images/behance/behance-test-system-06-110141da.png",
      "/work-images/behance/behance-test-system-10-469d6b8a.webp",
    ],
    stack: [
      "Figma",
      "UI Design",
      "UX Design",
      "test",
      "system design",
      "UI/UX",
      "ui design",
      "tests",
    ],
    detailSections: [
      {
        title: "Project Overview",
        text: "Test System is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        title: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, test, system design, UI/UX, ui design, tests. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        title: "Gallery Assets",
        text: "7 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
      {
        title: "Behance Details",
        text: "Source: Behance. Published: December 13, 2024. Last updated: December 26, 2024. Profile stats at scrape time: 32 Behance views and 4 appreciations. Original project URL: https://www.behance.net/gallery/214714449/Test-System.",
      },
    ],
    iconName: "Code2",
  },
  {
    title: "TAWSILA APP",
    slug: "behance-tawsila-app",
    href: "https://www.behance.net/gallery/210085207/TAWSILA-APP",
    source: "Behance",
    sourceUrl: "https://www.behance.net/gallery/210085207/TAWSILA-APP",
    client: "TAWSILA APP",
    type: "Figma Design",
    category: "figma-design",
    description:
      "TAWSILA APP is a Figma UI/UX design case study imported from Behance, published October 13, 2024, with focus areas including Figma, UI Design, UX Design, Driver app.",
    summary:
      "TAWSILA APP is a Figma UI/UX design case study imported from Behance, published October 13, 2024, with focus areas including Figma, UI Design, UX Design, Driver app.",
    scope: "Figma, UI Design",
    outcome: "Design case study",
    visual: "portfolio",
    span: "half",
    tone: "light",
    stats: ["Figma Design", "Figma"],
    year: "Behance",
    duration: "Design",
    team: "UI/UX design",
    headline: "TAWSILA APP",
    detailIntro:
      "TAWSILA APP is a Figma UI/UX design case study imported from Behance, published October 13, 2024, with focus areas including Figma, UI Design, UX Design, Driver app.",
    challenge:
      "TAWSILA APP is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
    build:
      "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, Driver app, car transport service, Vehicle Transportation, carservice, ui design. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
    impact:
      "Source: Behance. Published: October 13, 2024. Last updated: October 13, 2024. Profile stats at scrape time: 80 Behance views and 4 appreciations. Original project URL: https://www.behance.net/gallery/210085207/TAWSILA-APP.",
    modules: [
      "Figma",
      "UI Design",
      "UX Design",
      "Driver app",
      "car transport service",
      "Vehicle Transportation",
      "carservice",
      "ui design",
    ],
    outcomes: ["Figma design", "UI/UX case study", "Behance source"],
    timeline: [
      {
        label: "Project Overview",
        text: "TAWSILA APP is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        label: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, Driver app, car transport service, Vehicle Transportation, carservice, ui design. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        label: "Gallery Assets",
        text: "10 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
    ],
    thumbnail: "/work-images/behance/behance-tawsila-app-01-c4cee4b7.png",
    images: [
      "/work-images/behance/behance-tawsila-app-01-c4cee4b7.png",
      "/work-images/behance/behance-tawsila-app-02-8cdae080.webp",
      "/work-images/behance/behance-tawsila-app-03-f2726e8a.webp",
      "/work-images/behance/behance-tawsila-app-04-ad63695e.webp",
      "/work-images/behance/behance-tawsila-app-05-2be2bfa2.webp",
      "/work-images/behance/behance-tawsila-app-06-6ecc9dac.png",
      "/work-images/behance/behance-tawsila-app-07-c0bf5f38.webp",
      "/work-images/behance/behance-tawsila-app-08-eeb87712.png",
      "/work-images/behance/behance-tawsila-app-09-d8e144c4.webp",
      "/work-images/behance/behance-tawsila-app-10-2d992419.png",
    ],
    stack: [
      "Figma",
      "UI Design",
      "UX Design",
      "Driver app",
      "car transport service",
      "Vehicle Transportation",
      "carservice",
      "ui design",
    ],
    detailSections: [
      {
        title: "Project Overview",
        text: "TAWSILA APP is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        title: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, Driver app, car transport service, Vehicle Transportation, carservice, ui design. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        title: "Gallery Assets",
        text: "10 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
      {
        title: "Behance Details",
        text: "Source: Behance. Published: October 13, 2024. Last updated: October 13, 2024. Profile stats at scrape time: 80 Behance views and 4 appreciations. Original project URL: https://www.behance.net/gallery/210085207/TAWSILA-APP.",
      },
    ],
    iconName: "Code2",
  },
  {
    title: "Financial Dashboard",
    slug: "behance-financial-dashboard",
    href: "https://www.behance.net/gallery/206460079/Financial-Dashboard",
    source: "Behance",
    sourceUrl: "https://www.behance.net/gallery/206460079/Financial-Dashboard",
    client: "Financial Dashboard",
    type: "Figma Design",
    category: "figma-design",
    description:
      "Financial Dashboard is a Figma UI/UX design case study imported from Behance, published August 27, 2024, with focus areas including Figma, UI Design, UX Design, dashboard.",
    summary:
      "Financial Dashboard is a Figma UI/UX design case study imported from Behance, published August 27, 2024, with focus areas including Figma, UI Design, UX Design, dashboard.",
    scope: "Figma, UI Design",
    outcome: "Design case study",
    visual: "portfolio",
    span: "half",
    tone: "light",
    stats: ["Figma Design", "Figma"],
    year: "Behance",
    duration: "Design",
    team: "UI/UX design",
    headline: "Financial Dashboard",
    detailIntro:
      "Financial Dashboard is a Figma UI/UX design case study imported from Behance, published August 27, 2024, with focus areas including Figma, UI Design, UX Design, dashboard.",
    challenge:
      "Financial Dashboard is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
    build:
      "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, dashboard, financial, dashboard design, user interface, UI/UX. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
    impact:
      "Source: Behance. Published: August 27, 2024. Last updated: August 27, 2024. Profile stats at scrape time: 48 Behance views and 5 appreciations. Original project URL: https://www.behance.net/gallery/206460079/Financial-Dashboard.",
    modules: [
      "Figma",
      "UI Design",
      "UX Design",
      "dashboard",
      "financial",
      "dashboard design",
      "user interface",
      "UI/UX",
    ],
    outcomes: ["Figma design", "UI/UX case study", "Behance source"],
    timeline: [
      {
        label: "Project Overview",
        text: "Financial Dashboard is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        label: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, dashboard, financial, dashboard design, user interface, UI/UX. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        label: "Gallery Assets",
        text: "7 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
    ],
    thumbnail: "/work-images/behance/behance-financial-dashboard-01-e01fb34a.png",
    images: [
      "/work-images/behance/behance-financial-dashboard-01-e01fb34a.png",
      "/work-images/behance/behance-financial-dashboard-02-d6e964a4.webp",
      "/work-images/behance/behance-financial-dashboard-03-05b49c02.webp",
      "/work-images/behance/behance-financial-dashboard-04-e418ad83.png",
      "/work-images/behance/behance-financial-dashboard-05-606d779e.webp",
      "/work-images/behance/behance-financial-dashboard-06-0ddfbdf7.png",
      "/work-images/behance/behance-financial-dashboard-10-0c479288.webp",
    ],
    stack: [
      "Figma",
      "UI Design",
      "UX Design",
      "dashboard",
      "financial",
      "dashboard design",
      "user interface",
      "UI/UX",
    ],
    detailSections: [
      {
        title: "Project Overview",
        text: "Financial Dashboard is imported from Behance as a Figma design case study. The project is categorized under Figma designs so it can be browsed separately from websites and mobile/backend implementation work.",
      },
      {
        title: "Design Focus",
        text: "The scraped project tags and tools identify the work around Figma, UI Design, UX Design, dashboard, financial, dashboard design, user interface, UI/UX. These tags are preserved as capabilities on the detail page so visitors can quickly understand the product type, UI direction, and design craft involved.",
      },
      {
        title: "Gallery Assets",
        text: "7 Behance-hosted project images were downloaded into the local portfolio asset folder and attached to this case study. The detail page uses those local files for the hero preview and gallery instead of hotlinking remote Behance images.",
      },
      {
        title: "Behance Details",
        text: "Source: Behance. Published: August 27, 2024. Last updated: August 27, 2024. Profile stats at scrape time: 48 Behance views and 5 appreciations. Original project URL: https://www.behance.net/gallery/206460079/Financial-Dashboard.",
      },
    ],
    iconName: "Code2",
  },
] satisfies WorkItemInput[];
