import type { LucideIcon } from "lucide-react";
import { Boxes, Calculator, LineChart, PackageCheck, ScanBarcode, Truck } from "lucide-react";

export type BlogTopic = "ERP" | "Inventory" | "Warehouse" | "Accounting" | "POS" | "Automation";

export type BlogArticle = {
  slug: string;
  title: string;
  deck: string;
  topic: BlogTopic;
  readTime: string;
  publishedAt: string;
  audience: string;
  operatingQuestion: string;
  signals: { label: string; value: string }[];
  visual: "operations-board" | "warehouse-flow" | "finance-close" | "inventory-exceptions";
  icon: LucideIcon;
  detailSections?: string[];
  datePublished?: string;
  dateModified?: string;
};

export const blogArticles: BlogArticle[] = [
  {
    slug: "warehouse-management-software-egypt",
    title: "Warehouse software in Egypt: how to choose a system operators will use",
    deck: "A practical buying guide for teams comparing warehouse software, inventory accuracy, barcode workflows, receiving, picking, and delivery operations in Egypt.",
    topic: "Warehouse",
    readTime: "8 min read",
    publishedAt: "September 2026",
    audience: "Warehouse, logistics, commerce",
    operatingQuestion: "Can the system show the next action before the order reaches the floor?",
    visual: "warehouse-flow",
    icon: Truck,
    detailSections: ["operating-question", "buying-criteria", "egypt-context", "decision"],
    datePublished: "2026-09-23",
    dateModified: "2026-09-23",
    signals: [
      { label: "Priority", value: "Traceability" },
      { label: "Control", value: "Stock truth" },
      { label: "Output", value: "Faster dispatch" },
    ],
  },
  {
    slug: "digital-storefront-egypt",
    title: "Digital storefronts in Egypt need an operating system behind them",
    deck: "A digital storefront is only the front door. The useful work happens when catalog, inventory, payments, delivery, and customer data stay connected.",
    topic: "ERP",
    readTime: "6 min read",
    publishedAt: "September 2026",
    audience: "Commerce, founders, operations",
    operatingQuestion: "What should update automatically when a customer places an order?",
    visual: "operations-board",
    icon: ScanBarcode,
    detailSections: ["front-door", "source-of-truth", "operating-loop", "decision"],
    datePublished: "2026-09-23",
    dateModified: "2026-09-23",
    signals: [
      { label: "Front door", value: "Storefront" },
      { label: "Source", value: "Live inventory" },
      { label: "Outcome", value: "Joined-up orders" },
    ],
  },
  {
    slug: "ecommerce-software-egypt",
    title: "Ecommerce software in Egypt: connect the storefront to the work behind it",
    deck: "A practical guide to ecommerce software in Egypt: catalog, cash on delivery, payments, inventory, delivery, and the operating data that keeps orders moving.",
    topic: "ERP",
    readTime: "7 min read",
    publishedAt: "September 2026",
    audience: "Commerce, founders, operations",
    operatingQuestion: "Does every order create one shared operational record?",
    visual: "operations-board",
    icon: ScanBarcode,
    detailSections: [
      "storefront-is-not-system",
      "egypt-order-path",
      "integration-checklist",
      "decision",
    ],
    datePublished: "2026-09-24",
    dateModified: "2026-09-24",
    signals: [
      { label: "Demand", value: "COD + card" },
      { label: "Control", value: "Live stock" },
      { label: "Output", value: "Fewer handoffs" },
    ],
  },
  {
    slug: "laravel-rest-api-business-systems",
    title: "Laravel REST APIs for business systems: what to connect first",
    deck: "A practical guide to designing Laravel REST APIs for inventory, orders, payments, and mobile apps without turning every integration into a fragile handoff.",
    topic: "Automation",
    readTime: "7 min read",
    publishedAt: "September 2026",
    audience: "Product, engineering, operations",
    operatingQuestion: "Can every important business event be replayed, traced, and owned?",
    visual: "operations-board",
    icon: PackageCheck,
    detailSections: [
      "start-with-events",
      "resource-boundaries",
      "mobile-and-partners",
      "production-readiness",
    ],
    datePublished: "2026-09-24",
    dateModified: "2026-09-24",
    signals: [
      { label: "Contract", value: "Clear resources" },
      { label: "Reliability", value: "Idempotent events" },
      { label: "Output", value: "Safer integrations" },
    ],
  },
  {
    slug: "custom-business-software-egypt",
    title: "Custom business software in Egypt: when the workflow is the product",
    deck: "How to decide whether custom business software is justified when spreadsheets, SaaS tools, and manual approvals no longer agree.",
    topic: "ERP",
    readTime: "6 min read",
    publishedAt: "September 2026",
    audience: "Founders, COOs, operations",
    operatingQuestion: "Is the bottleneck a missing feature, or a missing operating model?",
    visual: "operations-board",
    icon: LineChart,
    detailSections: ["signal-to-build", "map-before-code", "buy-and-build", "first-release"],
    datePublished: "2026-09-24",
    dateModified: "2026-09-24",
    signals: [
      { label: "Trigger", value: "Repeated exceptions" },
      { label: "Scope", value: "First release" },
      { label: "Outcome", value: "Owned workflow" },
    ],
  },
  {
    slug: "custom-software-vs-off-the-shelf-egypt",
    title: "Custom software vs off-the-shelf in Egypt: a practical decision guide",
    deck: "The honest way to compare ready-made software with a system built around your workflow, budget, team, and long-term ownership.",
    topic: "ERP",
    readTime: "7 min read",
    publishedAt: "September 2026",
    audience: "Founders, COOs, operations",
    operatingQuestion: "Where does the generic tool stop helping and start taxing the operation?",
    visual: "operations-board",
    icon: LineChart,
    detailSections: ["start-with-ceiling", "total-cost", "ownership", "decision"],
    datePublished: "2026-09-24",
    dateModified: "2026-09-24",
    signals: [
      { label: "Question", value: "Buy or build" },
      { label: "Risk", value: "Workarounds" },
      { label: "Outcome", value: "Fit over features" },
    ],
  },
  {
    slug: "software-project-timeline-3-15-weeks",
    title: "Why custom software projects take 3 to 15 weeks",
    deck: "A clear way to think about software delivery timelines: what can ship in three weeks, what needs a longer runway, and what protects the first release.",
    topic: "Automation",
    readTime: "6 min read",
    publishedAt: "September 2026",
    audience: "Founders, product, operations",
    operatingQuestion: "What is the smallest release that changes the operation for the better?",
    visual: "operations-board",
    icon: PackageCheck,
    detailSections: ["scope-first", "three-week", "fifteen-week", "protect-the-timeline"],
    datePublished: "2026-09-24",
    dateModified: "2026-09-24",
    signals: [
      { label: "Range", value: "3–15 weeks" },
      { label: "Control", value: "Release boundary" },
      { label: "Output", value: "Working software" },
    ],
  },
  {
    slug: "post-launch-software-support-ownership",
    title: "Post-launch software support: who owns the system after release?",
    deck: "Why ownership, support, monitoring, and small improvements should be designed before custom software goes live.",
    topic: "Automation",
    readTime: "6 min read",
    publishedAt: "September 2026",
    audience: "Founders, operations, technology",
    operatingQuestion: "Who can explain the system when the business changes or something breaks?",
    visual: "operations-board",
    icon: PackageCheck,
    detailSections: ["ownership-after-launch", "support-model", "handover", "measure-improvement"],
    datePublished: "2026-09-24",
    dateModified: "2026-09-24",
    signals: [
      { label: "After launch", value: "Named owner" },
      { label: "Response", value: "Clear support" },
      { label: "Outcome", value: "Durable system" },
    ],
  },
  {
    slug: "egypt-gulf-software-integrations",
    title: "Software integrations for Egypt and the Gulf: design for the real handoffs",
    deck: "Local payment, delivery, language, and operational requirements matter when a business software system needs to work across Egypt, the Gulf, and international teams.",
    topic: "ERP",
    readTime: "7 min read",
    publishedAt: "September 2026",
    audience: "Commerce, logistics, operations",
    operatingQuestion: "Which local rule or partner can change the state of the business?",
    visual: "warehouse-flow",
    icon: Truck,
    detailSections: [
      "local-reality",
      "integration-boundaries",
      "regional-readiness",
      "international-without-generic",
    ],
    datePublished: "2026-09-24",
    dateModified: "2026-09-24",
    signals: [
      { label: "Reach", value: "Egypt + Gulf" },
      { label: "Control", value: "Owned integrations" },
      { label: "Output", value: "Fewer surprises" },
    ],
  },
  {
    slug: "before-another-dashboard",
    title: "What operators need before another dashboard",
    deck: "A practical look at approvals, stock events, and finance rules that should be mapped before interface design starts.",
    topic: "ERP",
    readTime: "7 min read",
    publishedAt: "June 2026",
    audience: "COO, finance, product",
    operatingQuestion: "Which handoffs should the system make impossible to miss?",
    visual: "operations-board",
    icon: LineChart,
    signals: [
      { label: "Handoffs", value: "Approvals" },
      { label: "Risk", value: "Exceptions" },
      { label: "Output", value: "Release map" },
    ],
  },
  {
    slug: "inventory-exceptions-are-requirements",
    title: "Inventory exceptions are product requirements",
    deck: "Variance, damaged stock, and partial receipts reveal the workflows generic inventory tools usually hide.",
    topic: "Inventory",
    readTime: "5 min read",
    publishedAt: "June 2026",
    audience: "Inventory, warehouse, finance",
    operatingQuestion: "What should happen when the count, receipt, and invoice disagree?",
    visual: "inventory-exceptions",
    icon: Boxes,
    signals: [
      { label: "Trigger", value: "Mismatch" },
      { label: "Owner", value: "Ops lead" },
      { label: "Output", value: "Audit trail" },
    ],
  },
  {
    slug: "finance-close-handoffs",
    title: "Designing finance closes around real handoffs",
    deck: "Month-end software works best when reconciliation, approvals, and audit trails are treated as one operating system.",
    topic: "Accounting",
    readTime: "6 min read",
    publishedAt: "May 2026",
    audience: "CFO, accounting, founders",
    operatingQuestion: "Which close tasks need evidence before the next team starts?",
    visual: "finance-close",
    icon: Calculator,
    signals: [
      { label: "Trigger", value: "Close task" },
      { label: "Owner", value: "Finance" },
      { label: "Output", value: "Evidence" },
    ],
  },
  {
    slug: "warehouse-speed-order-model",
    title: "Warehouse speed starts in the order model",
    deck: "Pick paths, wave planning, and dispatch accuracy all depend on decisions made before the floor sees the order.",
    topic: "Warehouse",
    readTime: "4 min read",
    publishedAt: "May 2026",
    audience: "Warehouse, logistics, commerce",
    operatingQuestion: "What does the floor need to know before a pick list exists?",
    visual: "warehouse-flow",
    icon: Truck,
    signals: [
      { label: "Trigger", value: "Order state" },
      { label: "Owner", value: "Warehouse" },
      { label: "Output", value: "Wave plan" },
    ],
  },
  {
    slug: "pos-data-is-operations-data",
    title: "POS data is operations data",
    deck: "Retail systems become useful when receipts, returns, stock, and settlement all update the same operating model.",
    topic: "POS",
    readTime: "5 min read",
    publishedAt: "April 2026",
    audience: "Retail, accounting, commerce",
    operatingQuestion: "Which store events should update stock and finance at the same time?",
    visual: "operations-board",
    icon: ScanBarcode,
    signals: [
      { label: "Trigger", value: "Store event" },
      { label: "Owner", value: "Retail ops" },
      { label: "Output", value: "Shared ledger" },
    ],
  },
  {
    slug: "automation-needs-operators",
    title: "Automation still needs an operator model",
    deck: "Good automation knows who owns an exception, when to stop, and what evidence the business needs later.",
    topic: "Automation",
    readTime: "6 min read",
    publishedAt: "April 2026",
    audience: "Ops, product, technology",
    operatingQuestion: "Where should automation pause instead of guessing?",
    visual: "inventory-exceptions",
    icon: PackageCheck,
    signals: [
      { label: "Trigger", value: "Rule break" },
      { label: "Owner", value: "Decision maker" },
      { label: "Output", value: "Controlled flow" },
    ],
  },
];

export const blogTopics: BlogTopic[] = [
  "ERP",
  "Inventory",
  "Warehouse",
  "Accounting",
  "POS",
  "Automation",
];

export function getBlogArticle(slug: string) {
  return blogArticles.find((article) => article.slug === slug);
}
